### PR TITLE
[fix error]: 'Unexpected token <'

### PR DESCRIPTION
**Pull request by YutHelloWorld**
image

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Does the `webpack-dev-server` still work if that line is removed?

What command are you using to run the server? And what URL are you navigating to in a web browser?

**Comment by YutHelloWorld** [comment]
`webpack-dev-server` still work comfotably. The command and URL would not change~

**Comment by ryan-roemer** [comment]
Actually what I meant is: Can you please type out the commands for the command line that I need to type and what I need to do in a browser so that I can see the error you are seeing?

Thanks!

**Comment by YutHelloWorld** [comment]
😂  type `yarn demo` in terminal & open `http://localhost:8080/` in browser(chrome). Open chrome devtool and you will see the error :)

**Comment by ryan-roemer** [comment]
Verified. Thanks!

**Pull request merged**
