### PR TITLE
Upgrade all dependencies and replace deprecated lifecycle method with componentDidUpdate

### LINKED ISSUE #19: Replace componentWillReceiveProps lifecycle method
The componentWillReceiveProps will be be marked UNSAFE with upcoming versions of Async React. Consider migrating this to componentWillReceiveProps or a supported alternative. I'm happy to raise a PR if this project is still being maintained.

### PR DESCRIPTION
**Pull request by brybrophy**
@ryan-roemer This pull request fixes #19 by replacing componentWillReceiveProps with componentDidUpdate. I also upgraded react, react-dom, enzyme, and enzyme-react-adapter-16 to the latest versions.

### CODE REVIEW

**Comment by brybrophy** [comment]
I decided to continue with this PR and use it to upgrade the dependencies in this project. Not sure why yet, but the build continues to fail on Travis. The build, tests, and demo are all working locally. I am wondering if the node_modules are being cached by Travis, since the error that is breaking the build there has to do with an old version of a package. I will see I I can get it working.

**Comment by brybrophy** [comment]
Got it! It was an issue with babel-jest having a bad peer dependency on babel-core 7.0.0, which was replaced by babel with @babel/core 7.0.1

Aside from upgrading dependencies, I also had to work on the tests, as Enzyme v3 changed the way it does things a bit. I fixed tests without changing their intentions, and add 1 more test into the suite.

@sarmeyer do you know if anyone is maintaining this project? I doesn't seem like it based on the commit history.

**Comment by ryan-roemer** [comment]
@brybrophy - I’m on parental leave and won’t be back for a few weeks. Thanks for this great work!!!

@boygirl - Can we find if someone has some time to verify and release this? Thanks!

**Comment by boygirl** [comment]
@brybrophy Thanks for this change! I tested locally, and everything is working as expected. Merging.

**Comment by brybrophy** [comment]
Great! Happy to help.

**Pull request merged**
